### ISSUE TITLE
Title doesnt work.

### ISSUE THREAD

**Issue by xXSirGamesXx** [PixelGuy75/JoinCommands#5]
whenever a player joins I get this error.

`[19:01:23] [Server thread/CRITICAL]: Could not execute task TitleJoin\Send: Call to undefined method pocketmine\Player::sendTitle()
[19:01:23] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::sendTitle()" (EXCEPTION) in "/plugins/DevTools1/src/TitleJoin/Main" at line 32
`

**Comment by thelucyclub** [comment]
That's not even this plugin. xD

**Comment by AvgZing** [comment]
Yup. wrong plugin.

**Comment by xXSirGamesXx** [comment]
oops xD meant to post this elsewhere

**Comment by AvgZing** [comment]
Please do. Don't forget to close the issue!
